name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
        name: Login to docker and push
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: frankisinfotech/buildME
          push: true
          tags: latest
